title: "Tina Wang"
description: "Sophomore at New York University studying Computer Science with a minor in Gender & Sexuality Studies. Passionate about social justice and tech."
about: "Sophomore at New York University studying Computer Science with a minor in Gender & Sexuality Studies. Passionate about social justice and tech."
location: "New York, NY"
email: xw1338@nyu.edu
baseurl: ""

url: "https://wang1998tina.github.io/" # replace by your site's url
twitter_username: callmetinafey
github_username:  wang1998tina
author: "Tina Wang"

# google analytics tracking code, please change the value
g_analytics: "UA-111535283-1"

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
resume_btn: "Resume"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
